name: genai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  fl_chart: 0.36.3
  awesome_dialog: ^3.2.1
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  geolocator: 12.0.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  uuid: ^4.4.2
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Lumanosimo
      fonts:
        - asset: fonts/Lumanosimo-Regular.ttf
