// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-mO52CKHjVx7AnJVztPXTH34vA-rTZbM',
    appId: '1:215360276901:web:c40be2e232442604fe004c',
    messagingSenderId: '215360276901',
    projectId: 'genai-aa516',
    authDomain: 'genai-aa516.firebaseapp.com',
    storageBucket: 'genai-aa516.appspot.com',
    measurementId: 'G-8G3BQWV3ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPXlKcj2_pe25CAQ7byiUVTKwDEV7xrsw',
    appId: '1:215360276901:android:c9588e3ec1cf3a0efe004c',
    messagingSenderId: '215360276901',
    projectId: 'genai-aa516',
    storageBucket: 'genai-aa516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJS1q4w0ySD_iBAsUoQGp9NUxcDkpGLBw',
    appId: '1:215360276901:ios:353ded532863ddb4fe004c',
    messagingSenderId: '215360276901',
    projectId: 'genai-aa516',
    storageBucket: 'genai-aa516.appspot.com',
    iosBundleId: 'com.example.genai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJS1q4w0ySD_iBAsUoQGp9NUxcDkpGLBw',
    appId: '1:215360276901:ios:353ded532863ddb4fe004c',
    messagingSenderId: '215360276901',
    projectId: 'genai-aa516',
    storageBucket: 'genai-aa516.appspot.com',
    iosBundleId: 'com.example.genai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-mO52CKHjVx7AnJVztPXTH34vA-rTZbM',
    appId: '1:215360276901:web:9eb86ab8cee232cdfe004c',
    messagingSenderId: '215360276901',
    projectId: 'genai-aa516',
    authDomain: 'genai-aa516.firebaseapp.com',
    storageBucket: 'genai-aa516.appspot.com',
    measurementId: 'G-HT3YHJF9PR',
  );
}
